name: r_cima_downloader
description: A modern media downloader app.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_inappwebview: ^6.1.5
  youtube_explode_dart: ^2.3.0
  http: ^1.2.0
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  video_player: ^2.8.2
  chewie: ^1.7.5
  local_auth: ^2.1.8
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.5
  flutter_local_notifications: ^17.0.0
  open_file_plus: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
